import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SdkView from '../components/SdkView'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
       <SdkView />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
