import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SdkView from '../components/SdkView'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Airnow APKs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <SdkView />
        <div className='notes mt-16 w-1/2'>
          <h2 className='text-lg font-bold'>Notes</h2>
          <p className="mb-4">I used <b>Next.js</b> to build this as it allows for extremely easy rapid prototyping of both frontend and backend (with easy-to-create REST API endpoints). It also uses <b>Tailwind CSS</b> and <b>DaisyUI</b> for the styling and UI/UX, <b>dayjs</b> for date parsing and display, and has Cypress for e2e/component testing.</p>
          <p className="mb-4">The SdkView component loads data upon first render using <code>useExpress</code> via <code>fetch</code> to the app's REST API, though there are any number of ways this could have been accomplished. The API simply returns the two JSON files, though of course a full app would accomplish this via database or service integration.</p>
          <p className="mb-4">The SDKs are ordered by category using a simple sort.</p>
          <p>I've included a state manager/provider via <code>context</code>, but honestly, without context for where this would be placed in an app, I didn't really see any particular place in this exact use case where it would be useful. The <code>SdkView</code> component fetches the data into its own state on load, and it doesn't need to persist that or its ui state elsewhere, does it? Let me know what I'm missing here. :-) </p>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
